version: "3.8"

services:
    client:
        image: mexator/client
        devices:
          - '/dev/fuse'
        cap_add:
          - SYS_ADMIN

    nameserver:
        image: mexator/nameserver

    fileserver:
        image: mexator/fileserver
        command: 'nameserver:3000 /data'
